on:
  push:
    branches:
      - sync
  pull_request:
  schedule:
    - cron: '0 0 0 1/1 *'

name: Sync

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Fetch upstream
        run: |
          git clone --depth=1 https://github.com/rollup/rollupjs.org rollup
      - name: Generate SUMMARY
        run: |
          set -x
          mkdir -p rollup/guide/zh/.github/workflows
          cp -a .github/workflows/gitbook.yaml rollup/guide/zh/.github/workflows/
          cp book.json rollup/guide/zh/
          cd rollup/guide/zh
          npm init -f
          npm install gitbook-summary
          npx book sm -t "[Rollup 中文文档](https://github.com/rollup/rollupjs.org)" -i node_modules
          rm -rf node_modules package.json package-lock.json
          ls -la
          cp 00-introduction.md README.md
      - name: Push docs src
        if: github.event_name == 'push'
        uses: docker://pcit/pages
        env:
          PCIT_EMAIL: khs1994@khs1994.com
          PCIT_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PCIT_GIT_URL: github.com/khs1994-website/rollup-docs.zh-cn
          PCIT_KEEP_HISTORY: "1"
          PCIT_LOCAL_DIR: rollup/guide/zh
          PCIT_MESSAGE: Sync from rollup/rollupjs.org by PCIT ${{ github.sha }}
          PCIT_TARGET_BRANCH: master
          PCIT_USERNAME: khs1994
